### ISSUE TITLE
第9章9.2The Recycler Adapter ,其中对Adapter的代码写了两次,需要修改

### ISSUE THREAD

**Issue by JamesLiAndroid** [wangjiegulu/kotlin-for-android-developers-zh#11]

**Comment by wangjiegulu** [comment]
原版中就是写了两遍的，两遍是有细微不同，第二遍是对第一遍的简化。
其中第二遍中使用了`items[position]`的方式访问`List`，还有使用`items.size`（直接访问属性）的方式来访问`size()`函数。
