### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by Zhang34** [wangjiegulu/kotlin-for-android-developers-zh#14]
+ 12.2 在主线程以外执行请求
"如果Activity已经被销毁了，这里就会奔溃"……“这样就不会在Activity销毁的时候遇到奔溃的情况了“；
还有最后一句的Toast拼错了

+ 28  “范型”
应该是“泛型”吧。

**Comment by wangjiegulu** [comment]
感谢提醒，已修改
