### ISSUE TITLE
Can we make it as gitbook so that we can read it efficiently?

### ISSUE THREAD

**Issue by JohnTsaiAndroid** [wangjiegulu/kotlin-for-android-developers-zh#15]
As you know,we can't change previous or next page convient now.So we can make it as gitbook.

**Comment by JohnTsaiAndroid** [comment]
Sorry,there is a gitbook version actually.But it jump to github and show as markdown file.In my opinion,it is not a gitbook.

**Comment by wangjiegulu** [comment]
https://wangjiegulu.gitbooks.io/kotlin-for-android-developers-zh/content/
