### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by Berial** [wangjiegulu/kotlin-for-android-developers-zh#20]
在The Recycler Adapter一节中的ForecastListAdapter代码中：
onCreateViewHolder方法少了一个表示结束的大括号；
onBindViewHolder方法中items.[position]应该为items[position]

**Comment by Berial** [comment]
还是这一节，"回到MainActivity，现在简单地创建一系列的String放入List中，然后使用创建分配Adapter实利。"一句的实利->实例。

**Comment by forever4313** [comment]
对头。

**Comment by wangjiegulu** [comment]
已修正，感谢指出
