### ISSUE TITLE
free翻译有误

### ISSUE THREAD

**Issue by lizwangying** [wangjiegulu/kotlin-for-android-developers-zh#23]
![image](https://cloud.githubusercontent.com/assets/13509775/19711638/b5438b16-9b69-11e6-986c-57319c08ae86.png)
应该是

> 自由的结合

**Comment by HerringtonDarkholme** [comment]
> **We have total integration with our daily IDE for free.** Android Studio can understand,
compile and run Kotlin code. And the support for this language comes from the company
who develops the IDE, so we Android developers are first-class citizens.

自由也是不准确的。从上下文来看，free在这里指的是不需要额外配置，Android Studio就可以支持Kotlin。 对应这里 http://www.merriam-webster.com/dictionary/free 第七条释义

> a :  not obstructed, restricted, or impeded <free to leave>
b :  not being used or occupied <waved with his free hand>
c :  not hampered or restricted in its normal operation

翻译成：
> Kontlin无需配置便能与日常使用的IDE完全整合

是比较妥当的

**Comment by ice1000** [comment]
@wangjiegulu

**Comment by ice1000** [comment]
@HerringtonDarkholme 才发现你是大哲学家

**Comment by lizwangying** [comment]
嗯嗯

**Comment by wangjiegulu** [comment]
@ice1000 @lizwangying 有道理有道理，马上改哈
