### ISSUE TITLE
我在fragment中使用id来操作控件，然后直接报空指针，为什么？

### ISSUE THREAD

**Issue by fansangg** [wangjiegulu/kotlin-for-android-developers-zh#51]
class GoodsDetailsFragment : BaseFragment(){
    
    

    override fun initView(inflater: LayoutInflater?, container: ViewGroup?): View {
        return inflater!!.inflate(R.layout.layout_fragment_goodsdetails, null)
    }

     override fun initData() {
         
        super.initData()
        val urlsList = arrayListOf<String>("xxxxxx")
        val itemList = ArrayList<GoodsDetailsItem>()
        (urlsList.indices).forEach{i ->
            itemList.add(GoodsDetailsItem(urlsList[i]))
        }
         
        val goodsDetailsAdapter = GoodsDetailsAdapter(R.layout.layout_fragment_goodsdetails_item, itemList)
        fragment_goodsdetails_img_recyclerview.layoutManager = LinearLayoutManager(mActivity)
        fragment_goodsdetails_img_recyclerview.isNestedScrollingEnabled = false
        fragment_goodsdetails_img_recyclerview.adapter = goodsDetailsAdapter

    }
    

}

为什么呢，有什么毛病吗？

**Comment by DaoBillTang** [comment]
需要在 onViewCreate之后 通过id调用才能定位到控件，在此之前 都是没有初始化这些控件的。
