### ISSUE TITLE
语句不通

### ISSUE THREAD

**Issue by amyliu1062** [wangjiegulu/kotlin-for-android-developers-zh#9]
5.介绍
“但是就算没有这个限制..”这句话语句不通，这是我的翻译，可以给你参考一下，“但是就算没有这个限制，如果新的安卓设备现在搭载的VM能够识别Java8，我们也要等到现在的安卓设备老到没有人使用，我们才能使用这样的新设备。我担心短时间内还无法做到。”

**Comment by wangjiegulu** [comment]
已解决
